[book]
authors = ["Gaurav Atreya"]
language = "en"
multilingual = false
src = "src"
title = "Network Analysis and Data Integration (NADI)"

[output.html]
additional-js = ["theme/syntax-highlight.js"]
smart-punctuation = true
mathjax-support = true

[output.html.code]
hidelines = { task = "!" }

[output.html.fold]
enable = true

[output.html.playground]
runnable = false
line-numbers = true

# this is really glitchy for now.
# [output.tectonic]
# latex    = true  # default = true
# pdf      = true  # default = true
# markdown = false  # default = true
